name: Marissa McHugh, Full Stack Developer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# email encoding
email:
  title: pbagnpg
  href: "znvygb:Fbgbz591@tznvy.pbz"

# icon links list
links:
  - name: linkedin
    url: https://www.linkedin.com/in/marissa-mchugh/
    class: fab fa-linkedin-in
  - name: twitter
    url: https://twitter.com/Sotom591
    class: fab fa-twitter
  - name: github
    url: https://github.com/Sotom591
    class: fab fa-github-alt
  - name: medium
    url: https://medium.com/@sotom591
    class: fab fa-medium-m
  - name: resume
    id: resume
    type: download
    url: https://sotom591.github.io/assets/resume/Marissa%20McHugh%20Resume.pdf
    class: fas fa-file-alt

uplink:
  - name: back to top
    url: https://sotom591.github.io/#home
    class: fas fa-arrow-alt-circle-up
